[p2p]
moniker = "local_node_3"
listen = "127.0.0.1"
port = 12121

[rest]
listen = "127.0.0.1"
port = 8067
tls_enabled = false

[logger]
level = "DEBUG"
max_file_size_MB = 100
max_backup_files = 100
max_retain_files_days = 28
use_console_logger = false
use_file_logger = true
compress = true

[swaps]
testnet = true
coin_1 = "BTC.B-918"
coin_2 = "BTC"
stake_coin = "FUEL-F7D"
# stake_amount must be boosted by 10^8 for BNB Chain (this is 100,000)
stake_amount = 10000000000000
fee_percent = 0.1

[tss]
threshold = 2
participants = 3
keygen_until = "2020-01-23T12:45:00Z"

[bnb]
rpc_uri = "tcp://data-seed-pre-0-s3.binance.org:80"
http_uri = "https://testnet-explorer.binance.org"
stake_tx = "744D9C26BD0A233D844F1C607E85D565C0E42C176B3B99C355CAA088926E0449"
stake_addr = "tbnb1xeym78qgl0e4y0rfhqt7cjpcznnwnpuc34ff88"
reward_addr = "tbnb1xeym78qgl0e4y0rfhqt7cjpcznnwnpuc34ff88"
fixed_out_fee = 500

[btc]
rpc_uri = ""
indexer_uri = "wss://testnet-indexer.swingby.network/ws"
reward_addr = "2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF"
fixed_out_fee = 30000
